export const LOADING_INIT = 'LOADING_INIT';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';

export const LOGIN_INIT = 'LOGIN_INIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA';

export const GET_ALL_USERS_INIT = 'GET_ALL_USERS_INIT';
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const CLEAR_ALL_USERS = 'CLEAR_ALL_USERS';

export const GET_ALL_INVESTORS_INIT = 'GET_ALL_INVESTORS_INIT';
export const GET_ALL_INVESTORS_ERROR = 'GET_ALL_INVESTORS_ERROR';
export const GET_ALL_INVESTORS_SUCCESS = 'GET_ALL_INVESTORS_SUCCESS';
export const CLEAR_ALL_INVESTORS = 'CLEAR_ALL_INVESTORS';

export const GET_LOANS_BY_INVESTOR_INIT = 'GET_LOANS_BY_INVESTOR_INIT';
export const GET_LOANS_BY_INVESTOR_ERROR = 'GET_LOANS_BY_INVESTOR_ERROR';
export const GET_LOANS_BY_INVESTOR_SUCCESS = 'GET_LOANS_BY_INVESTOR_SUCCESS';
export const CLEAR_LOANS_BY_INVESTOR = 'CLEAR_LOANS_BY_INVESTOR';

export const GET_ALL_CLIENTS_INIT = 'GET_ALL_CLIENTS_INIT';
export const GET_ALL_CLIENTS_ERROR = 'GET_ALL_CLIENTS_ERROR';
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS';
export const CLEAR_ALL_CLIENTS = 'CLEAR_ALL_CLIENTS';

export const GET_ALL_LOANS_INIT = 'GET_ALL_LOANS_INIT';
export const GET_ALL_LOANS_ERROR = 'GET_ALL_LOANS_ERROR';
export const GET_ALL_LOANS_SUCCESS = 'GET_ALL_LOANS_SUCCESS';
export const CLEAR_ALL_LOANS = 'CLEAR_ALL_LOANS';

export const GET_INVESTOR_INFO_INIT = 'GET_INVESTOR_INFO_INIT';
export const GET_INVESTOR_INFO_ERROR = 'GET_INVESTOR_INFO_ERROR';
export const GET_INVESTOR_INFO_SUCCESS = 'GET_INVESTOR_INFO_SUCCESS';
export const CLEAR_INVESTOR_INFO = 'CLEAR_INVESTOR_INFO';

export const SAVE_INVESTOR_PROFILE_INIT = 'SAVE_INVESTOR_PROFILE_INIT';
export const SAVE_INVESTOR_PROFILE_ERROR = 'SAVE_INVESTOR_PROFILE_ERROR';
export const SAVE_INVESTOR_PROFILE_SUCCESS = 'SAVE_INVESTOR_PROFILE_SUCCESS';
export const EDIT_INVESTOR_PROFILE = 'EDIT_INVESTOR_PROFILE';

export const GET_CLIENT_INFO_INIT = 'GET_CLIENT_INFO_INIT';
export const GET_CLIENT_INFO_ERROR = 'GET_CLIENT_INFO_ERROR';
export const GET_CLIENT_INFO_SUCCESS = 'GET_CLIENT_INFO_SUCCESS';
export const CLEAR_CLIENT_INFO = 'CLEAR_CLIENT_INFO';

export const SAVE_CLIENT_PROFILE_INIT = 'SAVE_CLIENT_PROFILE_INIT';
export const SAVE_CLIENT_PROFILE_ERROR = 'SAVE_CLIENT_PROFILE_ERROR';
export const SAVE_CLIENT_PROFILE_SUCCESS = 'SAVE_CLIENT_PROFILE_SUCCESS';
export const EDIT_CLIENT_PROFILE = 'EDIT_CLIENT_PROFILE';

export const GET_CLIENT_ZIPCODE_INIT = 'GET_CLIENT_ZIPCODE_INIT';
export const GET_CLIENT_ZIPCODE_ERROR = 'GET_PROFILE_ZIPCODE_ERROR';
export const GET_CLIENT_ZIPCODE_SUCCESS = 'GET_CLIENT_ZIPCODE_SUCCESS';

export const GET_PROVINCES_INIT = 'GET_PROVINCES_INIT';
export const GET_PROVINCES_ERROR = 'GET_PROVINCES_ERROR';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';

export const GET_CANTONS_INIT = 'GET_CANTONS_INIT';
export const GET_CANTONS_ERROR = 'GET_CANTONS_ERROR';
export const GET_CANTONS_SUCCESS = 'GET_CANTONS_SUCCESS';

export const GET_DISTRICTS_INIT = 'GET_DISTRICTS_INIT';
export const GET_DISTRICTS_ERROR = 'GET_DISTRICTS_ERROR';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICTS_SUCCESS';

// ======================

export const CHANGE_CLIENT_CURRENT_STEP = 'CHANGE_CLIENT_CURRENT_STEP';
export const CHANGE_INVESTOR_CURRENT_STEP = 'CHANGE_INVESTOR_CURRENT_STEP';
export const COMPLETE_CLIENT_STEP_ONE = 'COMPLETE_CLIENT_STEP_ONE';
export const COMPLETE_INVESTOR_STEP_ONE = 'COMPLETE_INVESTOR_STEP_ONE';
export const COMPLETE_CLIENT_STEP_TWO = 'COMPLETE_CLIENT_STEP_TWO';
export const COMPLETE_INVESTOR_STEP_TWO = 'COMPLETE_INVESTOR_STEP_TWO';
export const COMPLETE_CLIENT_STEP_THREE = 'COMPLETE_CLIENT_STEP_THREE';
export const INVESTOR_CHANGE_CURRENT_STEP = 'INVESTOR_CHANGE_CURRENT_STEP';

export const SET_CLIENT_INFORMATION = 'SET_CLIENT_INFORMATION';
export const STEP_CLIENT_DISABLED = 'STEP_CLIENT_DISABLED';
export const SET_INVESTOR_INFORMATION = 'SET_INVESTOR_INFORMATION';
export const STEP_INVESTOR_DISABLED = 'STEP_INVESTOR_DISABLED';

export const CLEAR_RECAPTCHA = 'CLEAR_RECAPTCHA';
export const SET_RECAPTCHA = 'SET_RECAPTCHA';

export const SET_EMAIL_VALUE = 'SET_EMAIL_VALUE';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const FORGOT_PASSWORD_INIT = 'FORGOT_PASSWORD_INIT';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const CLEAR_FORGOT_PASSWORD = 'CLEAR_FORGOT_PASSWORD';
export const CHANGE_PASSWORD_INIT = 'CHANGE_PASSWORD_INIT';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const GET_USER_ID_INIT = 'GET_USER_ID_INIT';
export const GET_USER_ID_SUCCESS = 'GET_USER_ID_SUCCESS';
export const GET_USER_ID_ERROR = 'GET_USER_ID_ERROR';

export const CLEAR_CONTACT_US_SEND_MSG = 'CLEAR_CONTACT_US_SEND_MSG';
export const CONTACT_US_SEND_MSG_SUCCESS = 'CONTACT_US_SEND_MSG_SUCCESS';
export const CONTACT_US_SEND_MSG_INIT = 'CONTACT_US_SEND_MSG_INIT';
export const CONTACT_US_SEND_MSG_ERROR = 'CONTACT_US_SEND_MSG_ERROR';

export const ADD_NEW_USER_INIT = 'ADD_NEW_USER_INIT';
export const ADD_NEW_USER_ERROR = 'ADD_NEW_USER_ERROR';
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';

export const ADD_NEW_CLIENT_INIT = 'ADD_NEW_CLIENT_INIT';
export const ADD_NEW_CLIENT_ERROR = 'ADD_NEW_CLIENT_ERROR';
export const ADD_NEW_CLIENT_SUCCESS = 'ADD_NEW_CLIENT_SUCCESS';

export const ADD_NEW_LOAN_INIT = 'ADD_NEW_LOAN_INIT';
export const ADD_NEW_LOAN_ERROR = 'ADD_NEW_LOAN_ERROR';
export const ADD_NEW_LOAN_SUCCESS = 'ADD_NEW_LOAN_SUCCESS';

export const CLEAR_CLIENT_SUBSCRIPTION = 'CLEAR_CLIENT_SUBSCRIPTION';

export const ADD_NEW_INVESTOR_INIT = 'ADD_NEW_INVESTOR_INIT';
export const ADD_NEW_INVESTOR_ERROR = 'ADD_NEW_INVESTOR_ERROR';
export const ADD_NEW_INVESTOR_SUCCESS = 'ADD_NEW_INVESTOR_SUCCESS';

export const CLEAR_INVESTOR_SUBSCRIPTION = 'CLEAR_INVESTOR_SUBSCRIPTION';

export const GET_CLIENT_PROFILE_INIT = 'GET_CLIENT_PROFILE_INIT';
export const GET_CLIENT_PROFILE_ERROR = 'GET_CLIENT_PROFILE_ERROR';
export const GET_CLIENT_PROFILE_SUCCESS = 'GET_CLIENT_PROFILE_SUCCESS';
export const CLEAR_CLIENT_PROFILE = 'CLEAR_CLIENT_PROFILE';

export const GET_INVESTOR_PROFILE_INIT = 'GET_INVESTOR_PROFILE_INIT';
export const GET_INVESTOR_PROFILE_ERROR = 'GET_INVESTOR_PROFILE_ERROR';
export const GET_INVESTOR_PROFILE_SUCCESS = 'GET_INVESTOR_PROFILE_SUCCESS';
export const CLEAR_INVESTOR_PROFILE = 'CLEAR_INVESTOR_PROFILE';

export const GET_LOAN_DATA_INIT = 'GET_LOAN_DATA_INIT';
export const GET_LOAN_DATA_ERROR = 'GET_LOAN_DATA_ERROR';
export const GET_LOAN_DATA_SUCCESS = 'GET_LOAN_DATA_SUCCESS';
export const CLEAR_LOAN_DATA = 'CLEAR_LOAN_DATA';

export const GET_OPPORTUNITIES_DATA_INIT = 'GET_OPPORTUNITIES_DATA_INIT';
export const GET_OPPORTUNITIES_DATA_ERROR = 'GET_OPPORTUNITIES_DATA_ERROR';
export const GET_OPPORTUNITIES_DATA_SUCCESS = 'GET_OPPORTUNITIES_DATA_SUCCESS';
export const CLEAR_OPPORTUNITIES_DATA = 'CLEAR_OPPORTUNITIES_DATA';

export const GET_LOAN_OPPORTUNITY_INIT = 'GET_LOAN_OPPORTUNITY_INIT';
export const GET_LOAN_OPPORTUNITY_ERROR = 'GET_LOAN_OPPORTUNITY_ERROR';
export const GET_LOAN_OPPORTUNITY_SUCCESS = 'GET_LOAN_OPPORTUNITY_SUCCESS';
export const CLEAR_LOAN_OPPORTUNITY = 'CLEAR_LOAN_OPPORTUNITY';

export const SET_INVESTORS = 'SET_INVESTORS';
export const SET_PERCENTAGE_INVERTED = 'SET_PERCENTAGE_INVERTED';

export const SAVE_INVEST_OPPORTUNITY_INIT = 'SAVE_INVEST_OPPORTUNITY_INIT';
export const SAVE_INVEST_OPPORTUNITY_ERROR = 'SAVE_INVEST_OPPORTUNITY_ERROR';
export const SAVE_INVEST_OPPORTUNITY_SUCCESS = 'SAVE_INVEST_OPPORTUNITY_SUCCESS';

export const GET_LOANS_MY_INVESTS_INIT = 'GET_LOANS_MY_INVESTS_INIT';
export const GET_LOANS_MY_INVESTS_ERROR = 'GET_LOANS_MY_INVESTS_ERROR';
export const GET_LOANS_MY_INVESTS_SUCCESS = 'GET_LOANS_MY_INVESTS_SUCCESS';
export const CLEAR_LOANS_MY_INVESTS = 'CLEAR_LOANS_MY_INVESTS';
